CREATE TABLE User (
UserID VARCHAR(255) NOT NULL,
Email VARCHAR(254) NOT NULL,
Password VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
DateJoined DATETIME NOT NULL,
Dob DATE NOT NULL,
Gender TINYINT(1),
CurrentLocation VARCHAR(255),
Phone VARCHAR(255),
ProfilePhoto VARBINARY(255),
PRIMARY KEY (UserID)
);

CREATE TABLE Circle (
AdminId VARCHAR(255) NOT NULL,
DateCreated DATE NOT NULL,
CircleTitle VARCHAR(255),
CirclePhoto VARBINARY(255),
PRIMARY KEY (AdminId)
);

CREATE TABLE CircleMembers (
CircleMemberID VARCHAR(255) NOT NULL,
CircleID VARCHAR(255) NOT NULL,
MemberUserID VARCHAR(255) NOT NULL,
DateJoined DATE NOT NULL,
PRIMARY KEY (MemberID)
);

CREATE TABLE PrivacySettings (
UserID VARCHAR(255) NOT NULL,
SearchVisibility INTEGER NOT NULL,
FriendVisibility INTEGER NOT NULL,
PRIMARY KEY (UserID)
);

CREATE TABLE Friendship (
FriendshipID VARCHAR(255) NOT NULL,
User1ID VARCHAR(255) NOT NULL,
User2ID VARCHAR(255) NOT NULL,
Status INTEGER NOT NULL,
Date DATETIME NOT NULL,
PRIMARY KEY (FriendshipID)
);

CREATE TABLE Message (
MessageID VARCHAR(255) NOT NULL,
SenderUserID VARCHAR(255) NOT NULL,
ReceiverType Integer NOT NULL,
ReceiverUserID VARCHAR(255) NOT NULL,
ReceiverGroupID VARCHAR(255) NOT NULL,
Content VARCHAR(25500) NOT NULL,
TimeSent DATETIME NOT NULL,
PRIMARY KEY (MessageID)
);

CREATE TABLE Photo (
PhotoID VARCHAR(255) NOT NULL,
UserID VARCHAR(255) NOT NULL,
Caption VARCHAR(25500),
DatePosted DATETIME NOT NULL,
AccessRights INTEGER NOT NULL,
Source VARCHAR(255) NOT NULL,
PRIMARY KEY (PhotoID)
);

CREATE TABLE PhotoCollection (
CollectionID VARCHAR(255) NOT NULL,
PhotoID VARCHAR(255) NOT NULL,
UserID VARCHAR(255) NOT NULL,
DatePhotoAdded DATE,
OwnerID VARCHAR(255) NOT NULL,
DateCreated DATETIME NOT NULL,
CollectionTitle VARCHAR(255) NOT NULL,
PRIMARY KEY (CollectionID)
);

CREATE TABLE PhotoComment (
PhotoCommentID VARCHAR(255) NOT NULL,
PhotoID VARCHAR(255) NOT NULL,
CommenterUserID VARCHAR(255) NOT NULL,
DatePosted DATETIME,
Content VARCHAR(25500) NOT NULL,
PRIMARY KEY (PhotoCommentID)
);

CREATE TABLE Blog (
BlogID INTEGER NOT NULL AUTO_INCREMENT,
UserID VARCHAR(255) NOT NULL,
DatePosted DATETIME,
Content VARCHAR(25500) NOT NULL,
AccessRights INTEGER NOT NULL,
PRIMARY KEY (BlogID)
);

CREATE TABLE BlogComment (
BlogCommentID VARCHAR(255) NOT NULL,
CommenterUserID VARCHAR(255) NOT NULL,
DatePosted DATETIME,
Content VARCHAR(25500) NOT NULL,
PRIMARY KEY (BlogCommentID)
);